
DROP TABLE IF EXISTS T_FUNCTION;

CREATE TABLE T_FUNCTION (
	ID_FUNCTION INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATIONDATE TIMESTAMP NOT NULL,
	MODIFICATIONDATE TIMESTAMP NULL
);

DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE (
	ID_ROLE INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATIONDATE TIMESTAMP NOT NULL,
	MODIFICATIONDATE TIMESTAMP NULL
);

DROP TABLE IF EXISTS T_USER;
CREATE TABLE T_USER (
	ID_USER INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	CODE_USER VARCHAR(50) NOT NULL,
	STATUS INT(1) NOT NULL,
	CREATIONDATE TIMESTAMP NOT NULL,
	MODIFICATIONDATE TIMESTAMP NULL
);

ALTER TABLE USER
ADD CONSTRAINT USER_FK_IDROLE
	FOREIGN KEY (IDROLE)
	REFERENCES 